**NUMPY TUTORIAL**

In [1]:
import numpy as np

In [2]:
parr = np.array([[1,2,3,3277]], np.int64)

In [3]:
parr.shape

(1, 4)

In [4]:
parr[0]

array([   1,    2,    3, 3277], dtype=int64)

In [5]:
parr[0,1]

2

In [6]:
parr.dtype

dtype('int64')

In [7]:
parr[0,1]=4

In [8]:
parr

array([[   1,    4,    3, 3277]], dtype=int64)

In [9]:
#ARRAY CREATION:CONVERSION FROM OTHER PYTHON STRUCTURES

In [10]:
listarray=np.array([[1,2,3], [5,6,5], [6,7,8]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 6, 5],
       [6, 7, 8]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,23,23})#dtype object it uses directory

array({34, 23}, dtype=object)

In [16]:
zeros=np.zeros((3,3))#3 by 3 ki array consisting zeros

In [17]:
zeros.dtype

dtype('float64')

In [18]:
rng=np.arange(15)#0se 15 tak elements ki list

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,50,4)# 1 se leke 50 tak 4 elements

In [21]:
lspace

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

In [22]:
emp=np.empty((4,6))#it gives empty array consisting of random numbers

In [23]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        9.45697982e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.78019761e-306, 1.37962185e-306],
       [1.78019625e-306, 6.89812281e-307, 9.34609790e-307,
        1.24610723e-306, 1.05700515e-307, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        3.22643519e-307, 9.79103798e-307, 2.46155235e-312]])

In [24]:
emp_like=np.empty_like(lspace)

In [25]:
emp_like

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

In [26]:
id=np.identity(4)#identity array of order 4by 4

In [27]:
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
id.shape

(4, 4)

In [29]:
arr=np.arange(81)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [31]:
arr.reshape(9,9)#9by 9 me reshape kardega

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [32]:
arr.ravel()#1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [33]:
x=[[1,2,3,4],[4,5,6,7],[7,1,0,4]]

In [34]:
ar=np.array(x)

In [35]:
ar

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 1, 0, 4]])

In [36]:
ar.sum(axis=0)#axis=0 means column 

array([12,  8,  9, 15])

In [37]:
ar.sum(axis=1) 

array([10, 22, 12])

In [38]:
ar.T#transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0],
       [4, 7, 4]])

In [39]:
ar.flat

In [40]:
for x in ar.flat:
    print(x)

1
2
3
4
4
5
6
7
7
1
0
4


In [41]:
ar.ndim #number of dimension

2

In [42]:
ar.size

12

In [43]:
ar.nbytes

48

In [44]:
ar.argmax

<function ndarray.argmax>

In [45]:
ar.argmax()

7

In [46]:
ar.argmin()

10

In [47]:
ar.argsort()#it sorts the element in the array by their postion

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [2, 1, 3, 0]], dtype=int64)

In [48]:
#below gives position only not the element

In [49]:
ar.argmax(axis=0)

array([2, 1, 1, 1], dtype=int64)

In [50]:
ar.argmax(axis=1)

array([3, 3, 0], dtype=int64)

In [51]:
ar.argmin(axis=0)

array([0, 2, 2, 0], dtype=int64)

In [52]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [53]:
ar.argsort(axis=0)#it is sorting column where position of the element are given on the basis of ascending order 

array([[0, 2, 2, 0],
       [1, 0, 0, 2],
       [2, 1, 1, 1]], dtype=int64)

In [54]:
ar

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 1, 0, 4]])

In [55]:
ar.ravel

<function ndarray.ravel>

In [56]:
ar.ravel()

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 1, 0, 4])

In [57]:
ar.reshape((6,2))

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7],
       [7, 1],
       [0, 4]])

In [58]:
ar

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 1, 0, 4]])

In [59]:
ar2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [60]:
ar+ar2

array([[ 2,  4,  6,  8],
       [ 9, 11, 13, 15],
       [16, 11, 11, 16]])

In [61]:
ar*ar2

array([[ 1,  4,  9, 16],
       [20, 30, 42, 56],
       [63, 10,  0, 48]])

In [62]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.64575131, 1.        , 0.        , 2.        ]])

In [63]:
ar

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 1, 0, 4]])

In [64]:
np.where(ar>6)

(array([1, 2], dtype=int64), array([3, 0], dtype=int64))

In [65]:
np.count_nonzero(ar)

11

In [66]:
np.count_nonzero(ar2)

12

In [67]:
np.nonzero(ar)#gives position where non zero elements are there in  ar i.e. (0,0),(0,1),(0,2),(0,3),(1,0),(1,1),(1,2).......

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 3], dtype=int64))

In [68]:
ar[0,1]=0

***Pandas tutorial***

In [69]:
import pandas as pd

In [70]:
import numpy as np

In [71]:
dict1={
    "name":['harry','subham','pranjal'],
    "marks":[89,90,99],
    "adress":['birgunj','hetauda','kathmandu']
}

In [72]:
df=pd.DataFrame(dict1)#changes to excell format

In [73]:
df

name  marks     adress
0    harry     89    birgunj
1   subham     90    hetauda
2  pranjal     99  kathmandu

In [74]:
df.to_csv('friends.csv')#changes to csv form

In [75]:
df.to_csv('friends_index.csv', index=False)#deletes the index

In [76]:
df.head(2)#prints the head 

name  marks   adress
0   harry     89  birgunj
1  subham     90  hetauda

In [77]:
df.tail(2)#prints the column

name  marks     adress
1   subham     90    hetauda
2  pranjal     99  kathmandu

In [78]:
df.describe()#describes the numerical column

marks
count   3.000000
mean   92.666667
std     5.507571
min    89.000000
25%    89.500000
50%    90.000000
75%    94.500000
max    99.000000

In [79]:
pranjal= pd.read_csv('pranjal.csv')#reads file from folder

In [80]:
pranjal['speed'][0]#shows which value is in the index 0

45

In [81]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
0             0           0     12345      harry     45    birgunj
1             1           1     67891     subham     90    hetauda
2             2           2     13222    pranjal     99  kathmandu

In [82]:
pranjal['speed']

0    45
1    90
2    99
Name: speed, dtype: int64

In [83]:
pranjal['speed'][0]=45

C:\Users\HP\AppData\Local\Temp\ipykernel_1388\3725862682.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pranjal['speed'][0]=45


In [84]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
0             0           0     12345      harry     45    birgunj
1             1           1     67891     subham     90    hetauda
2             2           2     13222    pranjal     99  kathmandu

In [85]:
pranjal.to_csv('pranjal.csv')

In [86]:
pranjal['train no'][2]

13222

In [87]:
pranjal['train no'][2]=13222

C:\Users\HP\AppData\Local\Temp\ipykernel_1388\1665086430.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pranjal['train no'][2]=13222


In [88]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
0             0           0     12345      harry     45    birgunj
1             1           1     67891     subham     90    hetauda
2             2           2     13222    pranjal     99  kathmandu

In [89]:
pranjal.to_csv('pranjal.csv')

In [90]:
pranjal.speed=[78,56,89]#this syntax can change anything

In [91]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
0             0           0     12345      harry     78    birgunj
1             1           1     67891     subham     56    hetauda
2             2           2     13222    pranjal     89  kathmandu

In [92]:
pranjal.index=['first','second','third']#changes index 

In [93]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
first              0           0     12345      harry     78    birgunj
second             1           1     67891     subham     56    hetauda
third              2           2     13222    pranjal     89  kathmandu

In [94]:
pranjal.index=['first','second','third']

In [95]:
pranjal

Unnamed: 0.1  Unnamed: 0  train no pilot name  speed     adress
first              0           0     12345      harry     78    birgunj
second             1           1     67891     subham     56    hetauda
third              2           2     13222    pranjal     89  kathmandu

In [96]:
ser=pd.Series(np.random.rand(34))

In [97]:
type(ser)

pandas.core.series.Series

In [98]:
ser

0     0.915845
1     0.277511
2     0.619333
3     0.975168
4     0.247673
5     0.135787
6     0.534515
7     0.940396
8     0.783636
9     0.269402
10    0.581354
11    0.950964
12    0.347790
13    0.560867
14    0.684142
15    0.164882
16    0.062925
17    0.723380
18    0.934595
19    0.296202
20    0.910340
21    0.817685
22    0.982004
23    0.870489
24    0.406591
25    0.456049
26    0.246701
27    0.414042
28    0.857435
29    0.179848
30    0.429611
31    0.357363
32    0.471823
33    0.066074
dtype: float64

In [99]:
newdf=pd.DataFrame(np.random.rand(334,5))#generate random number from 0-1of 334by 5 order

In [100]:
newdf

0         1         2         3         4
0    0.737146  0.241934  0.179161  0.581572  0.426221
1    0.724851  0.573840  0.703963  0.285495  0.874050
2    0.069039  0.624153  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113  0.561250  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [101]:
type(newdf)

pandas.core.frame.DataFrame

In [102]:
newdf.head()#prints head only

0         1         2         3         4
0  0.737146  0.241934  0.179161  0.581572  0.426221
1  0.724851  0.573840  0.703963  0.285495  0.874050
2  0.069039  0.624153  0.710759  0.164209  0.687675
3  0.446299  0.233823  0.618435  0.389579  0.179922
4  0.000149  0.144515  0.041252  0.921733  0.052663

In [103]:
newdf.describe()

0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.474388    0.478049    0.490853    0.456448    0.501095
std      0.295772    0.293219    0.286114    0.288330    0.286956
min      0.000149    0.000997    0.003936    0.000815    0.001534
25%      0.201255    0.220578    0.248400    0.208829    0.248198
50%      0.461331    0.474162    0.495159    0.442299    0.516121
75%      0.729787    0.743162    0.732418    0.682514    0.740431
max      0.997752    0.998867    0.998329    0.997017    0.993482

In [104]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [105]:
newdf[0][0] ="pranjal"

In [106]:
newdf.head()

0         1         2         3         4
0   pranjal  0.241934  0.179161  0.581572  0.426221
1  0.724851  0.573840  0.703963  0.285495  0.874050
2  0.069039  0.624153  0.710759  0.164209  0.687675
3  0.446299  0.233823  0.618435  0.389579  0.179922
4  0.000149  0.144515  0.041252  0.921733  0.052663

In [107]:
newdf[1][2]="sweeta"#changes in the dataframe

C:\Users\HP\AppData\Local\Temp\ipykernel_1388\2950907591.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[1][2]="sweeta"#changes in the dataframe


In [108]:
newdf.head()

0         1         2         3         4
0   pranjal  0.241934  0.179161  0.581572  0.426221
1  0.724851   0.57384  0.703963  0.285495  0.874050
2  0.069039    sweeta  0.710759  0.164209  0.687675
3  0.446299  0.233823  0.618435  0.389579  0.179922
4  0.000149  0.144515  0.041252  0.921733  0.052663

In [109]:
newdf.dtypes#shows datattypes

0     object
1     object
2    float64
3    float64
4    float64
dtype: object

In [110]:
newdf.index#shows index

RangeIndex(start=0, stop=334, step=1)

In [111]:
newdf.columns#SHOWS NUMBER OF COLUMN

RangeIndex(start=0, stop=5, step=1)

In [114]:
newdf.to_numpy()#if we change the strings to an integer its datatype will remain object

array([['pranjal', 0.24193409250598108, 0.17916078402547198,
        0.5815724677738664, 0.42622149671322607],
       [0.7248510034436979, 0.5738403162450623, 0.7039632688219651,
        0.285495127172971, 0.874049598649421],
       [0.06903939948337923, 'sweeta', 0.7107585036051649,
        0.16420928195833928, 0.6876754656203897],
       ...,
       [0.08111799403457454, 0.2928819275935759, 0.5285848477349108,
        0.13378836503415115, 0.4120327927335944],
       [0.24511305063892175, 0.5612503479258485, 0.885682158853012,
        0.16483355813252587, 0.5782853859430781],
       [0.7448272431033285, 0.03192129408883271, 0.7955659137394671,
        0.3863916902553104, 0.9206129012838311]], dtype=object)

In [116]:
newdf.T

0         1         2         3         4         5         6    \
0   pranjal  0.724851  0.069039  0.446299  0.000149  0.515695  0.677957   
1  0.241934   0.57384    sweeta  0.233823  0.144515  0.940784  0.649628   
2  0.179161  0.703963  0.710759  0.618435  0.041252  0.439874  0.797281   
3  0.581572  0.285495  0.164209  0.389579  0.921733  0.320489  0.481466   
4  0.426221   0.87405  0.687675  0.179922  0.052663  0.331373   0.67034   

        7         8         9    ...       324       325       326       327  \
0  0.229748  0.496091   0.48878  ...  0.336927   0.94776  0.731432   0.08956   
1  0.169525  0.925848  0.433827  ...  0.773334  0.825677  0.586242  0.264373   
2  0.637671  0.022131  0.254454  ...  0.737313  0.672844  0.304305  0.111156   
3  0.955162  0.156593  0.690836  ...  0.523256  0.241109   0.70031  0.026518   
4  0.268566  0.431436  0.190124  ...  0.165209  0.312237  0.436786  0.793903   

        328       329       330       331       332       333  
0  0.426155  0.935349  0.972089  0.081118  0.245113  0.744827  
1  0.712171  0.849615  0.122026  0.292882   0.56125  0.031921  
2  0.181047  0.142253  0.304454  0.528585  0.885682  0.795566  
3  0.638798  0.033243  0.572321  0.133788  0.164834  0.386392  
4  0.809359  0.192692  0.509655  0.412033  0.578285  0.920613  

[5 rows x 334 columns]

In [117]:
newdf

0         1         2         3         4
0     pranjal  0.241934  0.179161  0.581572  0.426221
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [121]:
newdf.sort_index(axis=1,ascending=False)#axis=0 means column by defaukt ascending is true but here it is false

4         3         2         1         0
0    0.426221  0.581572  0.179161  0.241934   pranjal
1    0.874050  0.285495  0.703963   0.57384  0.724851
2    0.687675  0.164209  0.710759    sweeta  0.069039
3    0.179922  0.389579  0.618435  0.233823  0.446299
4    0.052663  0.921733  0.041252  0.144515  0.000149
..        ...       ...       ...       ...       ...
329  0.192692  0.033243  0.142253  0.849615  0.935349
330  0.509655  0.572321  0.304454  0.122026  0.972089
331  0.412033  0.133788  0.528585  0.292882  0.081118
332  0.578285  0.164834  0.885682   0.56125  0.245113
333  0.920613  0.386392  0.795566  0.031921  0.744827

[334 rows x 5 columns]

In [122]:
 newdf.head()

0         1         2         3         4
0   pranjal  0.241934  0.179161  0.581572  0.426221
1  0.724851   0.57384  0.703963  0.285495  0.874050
2  0.069039    sweeta  0.710759  0.164209  0.687675
3  0.446299  0.233823  0.618435  0.389579  0.179922
4  0.000149  0.144515  0.041252  0.921733  0.052663

In [123]:
newdf[0]

0       pranjal
1      0.724851
2      0.069039
3      0.446299
4      0.000149
         ...   
329    0.935349
330    0.972089
331    0.081118
332    0.245113
333    0.744827
Name: 0, Length: 334, dtype: object

In [124]:
type(newdf[0])

pandas.core.series.Series

In [125]:
newdf.head()

0         1         2         3         4
0   pranjal  0.241934  0.179161  0.581572  0.426221
1  0.724851   0.57384  0.703963  0.285495  0.874050
2  0.069039    sweeta  0.710759  0.164209  0.687675
3  0.446299  0.233823  0.618435  0.389579  0.179922
4  0.000149  0.144515  0.041252  0.921733  0.052663

In [126]:
newdf2=newdf

In [127]:
newdf2[0][0]=987

C:\Users\HP\AppData\Local\Temp\ipykernel_1388\1365199539.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=987


In [130]:
newdf#newdf2 is just a view which changes values in newdf newdf2 is not a seperate until we use copy it just acts as a cursor 

0         1         2         3         4
0         987  0.241934  0.179161  0.581572  0.426221
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [131]:
newdf2=newdf.copy()

In [132]:
newdf2[0][0]=97835

C:\Users\HP\AppData\Local\Temp\ipykernel_1388\3030230984.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=97835


In [133]:
newdf2

0         1         2         3         4
0       97835  0.241934  0.179161  0.581572  0.426221
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [134]:
newdf

0         1         2         3         4
0         987  0.241934  0.179161  0.581572  0.426221
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [135]:
#we dont use tjis type of method to insert a number

In [136]:
newdf.loc[0,0]=654

In [137]:
newdf.columns=list('abcde')

In [138]:
newdf

a         b         c         d         e
0         654  0.241934  0.179161  0.581572  0.426221
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[334 rows x 5 columns]

In [141]:
newdf.loc[0,'a']=654

In [143]:
newdf.drop(0,axis=0)#remove an row or columm

a         b         c         d         e
1    0.724851   0.57384  0.703963  0.285495  0.874050
2    0.069039    sweeta  0.710759  0.164209  0.687675
3    0.446299  0.233823  0.618435  0.389579  0.179922
4    0.000149  0.144515  0.041252  0.921733  0.052663
5    0.515695  0.940784  0.439874  0.320489  0.331373
..        ...       ...       ...       ...       ...
329  0.935349  0.849615  0.142253  0.033243  0.192692
330  0.972089  0.122026  0.304454  0.572321  0.509655
331  0.081118  0.292882  0.528585  0.133788  0.412033
332  0.245113   0.56125  0.885682  0.164834  0.578285
333  0.744827  0.031921  0.795566  0.386392  0.920613

[333 rows x 5 columns]

In [147]:
newdf.loc[[1,2],['c','d']]#we use to seperate a dataframe from it

c         d
1  0.703963  0.285495
2  0.710759  0.164209

In [149]:
newdf.loc[[1,2],:]

a        b         c         d         e
1  0.724851  0.57384  0.703963  0.285495  0.874050
2  0.069039   sweeta  0.710759  0.164209  0.687675

In [150]:
newdf.loc[:,['c','d']]

c         d
0    0.179161  0.581572
1    0.703963  0.285495
2    0.710759  0.164209
3    0.618435  0.389579
4    0.041252  0.921733
..        ...       ...
329  0.142253  0.033243
330  0.304454  0.572321
331  0.528585  0.133788
332  0.885682  0.164834
333  0.795566  0.386392

[334 rows x 2 columns]